services:
  ggrep:
    build: .
    image: ${REPO:-docker.io/library}/ggrep:distroless
    ports:
      - "8080:8080"
    environment:
      - G_DEBUG=true
      - GGREP_BUFFER_SIZE=2000 # Configurable buffer size
    # We can override the command if needed, but default is server mode
    # command: ["/ggrep", "--server", "--port=8080"]
